---
kind: List
apiVersion: v1
metadata:
  name: jboss-kie-jdbc-extensions-image
  annotations:
    description: ImageStream definition for jdbc driver extension
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: jboss-kie-mysql-extension-openshift-image
    annotations:
      openshift.io/display-name: mysql driver extension
  spec:
    dockerImageRepository: quay.io/kiegroup/jboss-kie-mysql-extension-openshift-image
    tags:
    - name: '8.0.12'
      annotations:
        description: JBoss KIE custom mysql jdbc extension image, recommended version driver.
        tags: mysql,extension,jdbc,driver
        version: '8.0.12'
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: jboss-kie-postgresql-extension-openshift-image
    annotations:
      openshift.io/display-name: postgresql driver extension
  spec:
    dockerImageRepository: quay.io/kiegroup/jboss-kie-postgresql-extension-openshift-image
    tags:
    - name: '42.2.5'
      annotations:
        description: JBoss KIE custom mysql jdbc extension image, recommended version driver.
        tags: postgresql,extension,jdbc,driver
        version: '42.2.5'
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: jboss-kie-mariadb-extension-openshift-image
    annotations:
      openshift.io/display-name: mariadb driver extension
  spec:
    dockerImageRepository: quay.io/kiegroup/jboss-kie-mariadb-extension-openshift-image
    tags:
    - name: '2.3.0'
      annotations:
        description: JBoss KIE custom mysql jdbc extension image, recommended version driver.
        tags: mariadb,extension,jdbc,driver
        version: '2.3.0'